// <auto-generated-by>GitHub Copilot</auto-generated-by>
using System.Runtime.InteropServices;
using System.Text;

namespace WitpaeTheaterStaff.DllInterface;

/// <summary>Thrown when the game DLLs cannot be loaded.</summary>
public sealed class DllNotAvailableException : Exception
{
    /// <inheritdoc/>
    public DllNotAvailableException(string message) : base(message) { }

    /// <inheritdoc/>
    public DllNotAvailableException(string message, Exception inner) : base(message, inner) { }
}

/// <summary>
/// Manages loading the WITPAE 32-bit game DLLs and calling their exported
/// <c>GetRecInfo</c> function to return pointers into the DLL's internal
/// record arrays.
/// </summary>
/// <remarks>
/// <para>
/// Both <c>pwsdll.dll</c> and <c>pwsdll7.dll</c> must be present in
/// <paramref name="dllDir"/>.  The constructor will throw
/// <see cref="DllNotAvailableException"/> if the process is not 32-bit or if
/// the DLL files cannot be found or loaded.
/// </para>
/// <para>
/// Struct layout notes: all P/Invoke structs in <see cref="PwsDllStructs"/>
/// use <c>LayoutKind.Sequential</c> without an explicit <c>Pack</c> value so
/// the CLR uses natural alignment — matching Python <c>ctypes</c> default
/// behaviour, which was verified against actual game save files in the
/// <c>pywitpaescraper</c> project.
/// </para>
/// </remarks>
public sealed class PwsDll : IDisposable
{
    // ── DLL function delegate ─────────────────────────────────────────────
    [UnmanagedFunctionPointer(CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
    private delegate IntPtr GetRecInfoDelegate(string saveFile, int recType);

    private IntPtr _dllHandle;
    private IntPtr _dll7Handle;
    private GetRecInfoDelegate? _getRecInfo;
    private bool _disposed;

    /// <summary>
    /// Loads <c>pwsdll.dll</c> and <c>pwsdll7.dll</c> from <paramref name="dllDir"/>.
    /// </summary>
    /// <param name="dllDir">
    /// Directory that contains both DLL files (typically the WITPAE game
    /// installation directory).
    /// </param>
    /// <exception cref="DllNotAvailableException">
    /// Thrown when the process is not 32-bit, the DLL files are missing, or
    /// the DLL cannot be loaded.
    /// </exception>
    public PwsDll(string dllDir)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(dllDir);

        if (IntPtr.Size != 4)
            throw new DllNotAvailableException(
                $"WITPAE DLLs require a 32-bit process; this process is {IntPtr.Size * 8}-bit. " +
                "Compile with PlatformTarget=x86.");

        LoadDlls(dllDir);
    }

    // ── Public typed accessors ────────────────────────────────────────────

    /// <summary>Returns a pointer to the scenario info block in <paramref name="saveFile"/>.</summary>
    public IntPtr GetScenarioInfoPtr(string saveFile) =>
        CallGetRecInfo(saveFile, (int)RecType.Scenario);

    /// <summary>Returns a pointer to the ship array in <paramref name="saveFile"/>.</summary>
    public IntPtr GetShipPtr(string saveFile) =>
        CallGetRecInfo(saveFile, (int)RecType.Ship);

    /// <summary>Returns a pointer to the ship-class array in <paramref name="saveFile"/>.</summary>
    public IntPtr GetShipClassPtr(string saveFile) =>
        CallGetRecInfo(saveFile, (int)RecType.ShipClass);

    /// <summary>Returns a pointer to the air-group array in <paramref name="saveFile"/>.</summary>
    public IntPtr GetAirGroupPtr(string saveFile) =>
        CallGetRecInfo(saveFile, (int)RecType.AirGroup);

    /// <summary>Returns a pointer to the aircraft-type array in <paramref name="saveFile"/>.</summary>
    public IntPtr GetAircraftPtr(string saveFile) =>
        CallGetRecInfo(saveFile, (int)RecType.Aircraft);

    /// <summary>Returns a pointer to the location array in <paramref name="saveFile"/>.</summary>
    public IntPtr GetLocationPtr(string saveFile) =>
        CallGetRecInfo(saveFile, (int)RecType.Location);

    /// <summary>Returns a pointer to the leader array in <paramref name="saveFile"/>.</summary>
    public IntPtr GetLeaderPtr(string saveFile) =>
        CallGetRecInfo(saveFile, (int)RecType.Leader);

    /// <summary>Returns a pointer to the pilot array in <paramref name="saveFile"/>.</summary>
    public IntPtr GetPilotPtr(string saveFile) =>
        CallGetRecInfo(saveFile, (int)RecType.Pilot);

    /// <summary>Returns a pointer to the device array in <paramref name="saveFile"/>.</summary>
    public IntPtr GetDevicePtr(string saveFile) =>
        CallGetRecInfo(saveFile, (int)RecType.Device);

    /// <summary>Returns a pointer to the task-group array in <paramref name="saveFile"/>.</summary>
    public IntPtr GetTaskGroupPtr(string saveFile) =>
        CallGetRecInfo(saveFile, (int)RecType.TaskForce);

    /// <summary>Returns a pointer to the scenario info block in <paramref name="saveFile"/>.</summary>
    public IntPtr GetScenInfoPtr(string saveFile) =>
        CallGetRecInfo(saveFile, (int)RecType.Scenario);

    // ── Typed iteration helpers ───────────────────────────────────────────

    /// <summary>
    /// Iterates records of type <typeparamref name="T"/> starting at
    /// <paramref name="basePtr"/>, stopping when <paramref name="isEmpty"/>
    /// returns <see langword="true"/> or <paramref name="maxCount"/> is reached.
    /// </summary>
    public static IEnumerable<(int Index, T Record)> IterateRecords<T>(
        IntPtr basePtr,
        Func<T, bool> isEmpty,
        int maxCount = 10_000)
        where T : struct
    {
        if (basePtr == IntPtr.Zero)
            yield break;

        int stride = Marshal.SizeOf<T>();
        for (int i = 0; i < maxCount; i++)
        {
            var record = Marshal.PtrToStructure<T>(basePtr + i * stride);
            if (isEmpty(record))
                yield break;
            yield return (i, record);
        }
    }

    // ── String decoding helper ────────────────────────────────────────────

    /// <summary>
    /// Decodes a null-terminated Latin-1 C string from a fixed-size byte array.
    /// </summary>
    public static string CStr(byte[]? bytes)
    {
        if (bytes == null || bytes.Length == 0)
            return string.Empty;
        int len = Array.IndexOf(bytes, (byte)0);
        if (len < 0) len = bytes.Length;
        return Encoding.Latin1.GetString(bytes, 0, len).Trim();
    }

    // ── Internal helpers ──────────────────────────────────────────────────

    private void LoadDlls(string dllDir)
    {
        string pwsdllPath  = Path.Combine(dllDir, "pwsdll.dll");
        string pwsdll7Path = Path.Combine(dllDir, "pwsdll7.dll");

        if (!File.Exists(pwsdllPath))
            throw new DllNotAvailableException($"DLL not found: {pwsdllPath}");
        if (!File.Exists(pwsdll7Path))
            throw new DllNotAvailableException($"DLL not found: {pwsdll7Path}");

        try
        {
            _dllHandle  = NativeLibrary.Load(pwsdllPath);
            _dll7Handle = NativeLibrary.Load(pwsdll7Path);
        }
        catch (Exception ex)
        {
            throw new DllNotAvailableException($"Failed to load DLLs from {dllDir}: {ex.Message}", ex);
        }

        IntPtr fnPtr = NativeLibrary.GetExport(_dllHandle, "GetRecInfo");
        _getRecInfo = Marshal.GetDelegateForFunctionPointer<GetRecInfoDelegate>(fnPtr);
    }

    private IntPtr CallGetRecInfo(string saveFile, int recType)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        if (_getRecInfo is null)
            throw new DllNotAvailableException("DLLs not loaded.");

        IntPtr result = _getRecInfo(saveFile, recType);
        if (result == IntPtr.Zero)
            throw new InvalidOperationException(
                $"GetRecInfo returned null for recType={recType}, file={saveFile}");
        return result;
    }

    /// <inheritdoc/>
    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        _getRecInfo = null;
        if (_dllHandle  != IntPtr.Zero) { NativeLibrary.Free(_dllHandle);  _dllHandle  = IntPtr.Zero; }
        if (_dll7Handle != IntPtr.Zero) { NativeLibrary.Free(_dll7Handle); _dll7Handle = IntPtr.Zero; }
    }
}
